name: supp
description: A widget which displays an image, a title, and a subtitle for errors, empty states, or just fancy custom messages.
version: 1.3.0
homepage: https://github.com/xiprox/sup

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
